### ISSUE TITLE
Hide Github credentials in 'gem from' output

### ISSUE THREAD

**Issue by danielpclark** [bundler/bundler-features#111] opened 2016-02-07 00:23 UTC
When adding a private repository to pull gems from with either username & password or OAuth key with permissions the credentials get put before the url.  When running the `bundle` command the complete URL is displayed for each Github gem including secret credentials and keys.  This can be problematic if peolple use any credentials in a public environment or when screenshots get taken for freelance work like with UpWork.  Can you shorten the printed output of repository servers to exclude the pre-domain credentials?

Example:

```ruby
git "https://#{ENV['GITHUB_CREDENTIALS']}:x-oauth-basic@github.com/company/private-repo" do
  gem 'be_excellent', ref: '83623'
  gem 'to_eachother', ref: '8886c'
end
```

```
bundle
Using be_excellent 0.0.1 from https://ALL_YOUR_SECRETS_REVEALED!:x-oauth-basic@github.com/company/private-repo (at master@53534b2)
```

**Comment by RochesterinNYC** [comment] 2016-02-07 19:22
Out of curiosity, does this still happen when using `bundle config`? Introduced in bundler/bundler#3898

**Comment by danielpclark** [comment] 2016-02-08 03:40
Changing the repo config to this first:

    git "https://github.com/company/private-repo" do
      gem 'be_excellent', ref: '83623'
      gem 'to_eachother', ref: '8886c'
    end

And trying this with OAuth `bundle config https://github.com/bundler/bundler.git abcd0123generatedtoken:x-oauth-basic` did not work.  But setting `export BUNDLE_GITHUB__COM=abcd0123generatedtoken:x-oauth-basic` made the above configuration work without showing credentials.

So yes this does work.

**Comment by RochesterinNYC** [comment] 2016-02-08 05:23
I think you might have to swap out `https://github.com/bundler/bundler.git` with the corresponding url for the repo? So `bundle config https://github.com/company/private-repo.git abcd0123generatedtoken:x-oauth-basic`

**Comment by danielpclark** [comment] 2016-02-09 02:09
Yes.  I think what I had done was `company/private-repo` instead of `company/private-repo.git` on the bundle config parameters.  With the `.git` extension it works.

**Comment by RochesterinNYC** [comment] 2016-02-09 04:46
Oh okay, gotcha. Anything else regarding this feature request or do you think it can be marked as closed?

**Comment by danielpclark** [comment] 2016-02-10 21:42
I suppose some instructions in the README or something very public would be nice.  I went down a few rabbit holes to find how to do this and didn't initially find the cleanest way.

**Comment by RochesterinNYC** [comment] 2016-02-10 23:08
Maybe an added section like `Managing Credentials` to the `Help with` section on http://bundler.io/ ?

**Comment by danielpclark** [comment] 2016-02-10 23:56
Yes please :+1:  :smile:

**Comment by danielpclark** [comment] 2016-02-25 13:30
I've found that the settings that worked on my development machine aren't working on Heroku.  I set the same environment variable that `~/.bundle/config` had `BUNDLE_HTTPS://GITHUB__COM/COMPANY/PRIVATE-REPO__GIT/: long-hex-number:x-oauth-basic` but Heroku is giving me this error message.

    fatal: could not read Username for 'https://github.com': No such device or address

Is there another environment variable I need to set for this?

**Comment by danielpclark** [comment] 2016-02-25 14:16
I found the issue.  Heroku ENV variables don't support the special characters used in a URL.  I'll need to manually have the Bundler.settings value set.

**Comment by danielpclark** [comment] 2016-02-25 21:33
Well, I went back to my original configuration

```ruby
git "https://#{ENV['GITHUB_CREDENTIALS']}:x-oauth-basic@github.com/company/private-repo.git" do
  gem 'be_excellent', ref: '83623'
  gem 'to_eachother', ref: '8886c'
end
```

Heroku works with this.  And I'm back to my original feature request. ... Oh well :frowning:

**Comment by indirect** [comment] 2016-02-25 21:40
@danielpclark sounds like it might be worth complaining to Heroku about how they don't allow valid ENV to be set? When we implemented this, I thought we might need to remove or replace URL characters, but Unix shells all support them without any problems. :/

We should already have the helper methods needed to accomplish this, written for gem server URLs. @RochesterinNYC, interested in hooking them up for git repos as well?

**Comment by danielpclark** [comment] 2016-02-25 22:21
@indirect I was considering doing just that and I dug into Heroku docs one last time and found an alternate environment variable config they allow.

> The .env file lets you capture all the config vars that you need in order to run your app locally. When you start your app using any of the heroku local commands, the .env file is read, and each name/value pair is inserted into the environment, to mimic the action of config vars. -[Heroku](https://devcenter.heroku.com/articles/heroku-local#set-up-your-local-environment-variables)

So I added `BUNDLE_HTTPS://GITHUB__COM/COMPANY/PRIVATE-REPO__GIT/=long-hex-number:x-oauth-basic` to the **.env** file and switched my Gemfile back to.

```ruby
git "https://github.com/company/private-repo.git" do
  gem 'be_excellent', ref: '83623'
  gem 'to_eachother', ref: '8886c'
end
```

And it works. :smiley:   So the important thing to note is using the standard Heroku ENV settings in their dashboard or via the Heroku Toolbelt won't allow the Bundler URL environment variables and we need to use the **.env** file.

This should be enough info for the `Managing Credentials` section @RochesterinNYC suggested.

**Comment by RochesterinNYC** [comment] 2016-02-26 05:35
@indirect sure, I'll take a look at it this weekend, along with starting to draft up a `Managing Credentials` section/page. Which helper methods are you referring to?

**Comment by rwz** [comment] 2016-02-26 18:40
Damn, I never thought shell would allow that:

```
~ > ruby -e 'ENV["BUNDLE_HTTPS://GITHUB__COM/COMPANY/PRIVATE-REPO__GIT/"]="foo"; exec "sh"'
sh-3.2$ env | grep -i github
BUNDLE_HTTPS://GITHUB__COM/COMPANY/PRIVATE-REPO__GIT/=foo
```

**Comment by mikehale** [comment] 2016-02-26 18:47
It seems that while technically other characters are allowed anything besides alpha-numeric and underscores are a bit exotic: http://unix.stackexchange.com/a/93533

**Comment by mikehale** [comment] 2016-02-26 18:50
> @danielpclark sounds like it might be worth complaining to Heroku about how they don't allow valid ENV to be set? When we implemented this, I thought we might need to remove or replace URL characters, but Unix shells all support them without any problems. :/

Would it be possible to stick to alphanumeric and underscores for this? It seems like there really isn't a good way to work with other characters in a standard way.

Example: 
```
bash-3.2$ export BUNDLE_HTTPS:=foo
bash: export: `BUNDLE_HTTPS:=foo': not a valid identifier
```

**Comment by danielpclark** [comment] 2016-02-26 22:32
I just wrote a gem for converting to and from ENV friendly variables.  [EnvCompat](https://github.com/danielpclark/env_compat)

You're more than welcome to use the code in anyway for Bundler.  If you want you can copy and paste and change the code in your own code base.  If you do so I would appreciate a comment crediting me with a URL to the original source code.

Here's what it does:
```ruby
EnvCompat.encode "https://github.com/company/private-repo.git"
# => "HTTPS_CFF_GITHUB_D_COM_F_COMPANY_F_PRIVATE_M_REPO_D_GIT" 

EnvCompat.decode "HTTPS_CFF_GITHUB_D_COM_F_COMPANY_F_PRIVATE_M_REPO_D_GIT" 
# => HTTPS://GITHUB.COM/COMPANY/PRIVATE-REPO.GIT
```

**Comment by segiddins** [comment] 2016-02-26 22:37
@danielpclark the issue is unambiguously determining _how_ to decode a given string

**Comment by danielpclark** [comment] 2016-02-26 22:40
I'm not sure what you mean by "unambiguously".  Your code base marks all relevant environment variables with a preceding `BUNDLE_`.  After you chop that off the EnvCompat code uses the underscore just like html tags `<` and `>`... everything within matching underscores is code for a symbol.

**Comment by segiddins** [comment] 2016-02-26 22:41
How do you now that `_F_` isn't a part of the URL though? You can't.

**Comment by danielpclark** [comment] 2016-02-26 22:45
Because the gem toggles when code blocks (the underscore tags) are on.  `_F_` would be translated into `_U_F_U_`.  That will encode and decode without any issues.

**Comment by TimMoore** [comment] 2016-02-27 05:08
Sorry for chiming in late on this, but Bundler already supports an alternate form for environment variables, as described in http://bundler.io/man/bundle-config.1.html#CREDENTIALS-FOR-GEM-SOURCES

I'm not totally positive whether that works for git sources, but I believe so... actually @danielpclark I'm a little puzzled by your comment:

> But setting export BUNDLE_GITHUB__COM=abcd0123generatedtoken:x-oauth-basic made the above configuration work without showing credentials.

It sounds like that _did_ work, and would be compatible with Heroku, so I'm not sure what the issue is?

**Comment by danielpclark** [comment] 2016-02-27 05:58
@TimMoore The context of that is a physical file named **.env** which gets published to a git repository.  That is insecure.  True environment variables are not saved in git commits and are kept separate from the code base.

**Comment by danielpclark** [comment] 2016-02-27 06:17
@TimMoore That worked on my development machine.  From there I had tried copying the settings directly from the ~/.bundle/config file to my Heroku ENV settings.  So I had used `BUNDLE_HTTPS://GITHUB__COM/COMPANY/PRIVATE-REPO__GIT/` instead of `BUNDLE_GITHUB__COM`.  Which is what led to all the problems I've had.

Thank you for pointing it out.  I've switched my Heroku ENV to the correct setting and it works.  I feel a bit foolish that it went this far.  But I do need my humble pie once in a while.  Hopefully much good has come of this with all the information here for managing credentials and a new gem.

Thanks again Tim for pointing that out.

**Comment by TimMoore** [comment] 2016-02-27 06:52
Awesome, glad you got it working! :+1:

**Closed** 2016-02-27 23:46 UTC

**Comment by RochesterinNYC** [comment] 2016-03-01 05:19
@indirect does your [comment](https://github.com/bundler/bundler-features/issues/111#issuecomment-188999169) about gem server url helper methods and porting/using them for git repos still apply?

**Comment by indirect** [comment] 2016-03-01 05:25
@RochesterinNYC I would still happily accept a pull request that sanitizes urls when they are printed out, yes.
