### ISSUE TITLE
 Message from application: no such file to load -- bundler/setup (LoadError)   /usr/lib64/ruby/gems/1.8/gems/passenger-5.0.23/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:430:in `require'   /usr/lib64/ruby/gems/1.8/gems/passenger-5.0.23/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'   /usr/lib64/ruby/gems/1.8/gems/passenger-5.0.23/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:297:in `run_load_path_setup_code'   /usr/lib64/ruby/gems/1.8/gems/passenger-5.0.23/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'   /usr/lib64/ruby/gems/1.8/gems/passenger-5.0.23/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code'   /usr/lib64/ruby/gems/1.8/gems/passenger-5.0.23/src/helper-scripts/rack-preloader.rb:100:in `preload_app'   /usr/lib64/ruby/gems/1.8/gems/passenger-5.0.23/src/helper-scripts/rack-preloader.rb:156

### ISSUE THREAD

**Issue by haussyb** [bundler/bundler-features#107] opened 2016-02-03 10:05 UTC

**Comment by TimMoore** [comment] 2016-02-03 11:47
Duplicate of #106

**Closed** 2016-02-03 11:46 UTC
